all:
     gcc -o balcao  balcao.c -pthread
     gcc -o cliente cliente.c -pthread
     gcc -o medico medico.c -pthread
balcao:
     gcc -o balcao balcao.c
cliente:
     gcc -o cliente cliente.c
medico:
     gcc -o medico medico.c
clean:
     rm balcao medico cliente